/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignmentone;

import java.util.Scanner;

// import org.checkerframework.checker.units.qual.min;

/**
 * This is the main class for the assignment.
 */
public class App {
  private Scanner input;

  private App(Scanner scannerInput) {
    this.input = scannerInput;
  }

  public void helloThere() {
    System.out.print("Name, please: ");
    String name = input.nextLine();

    HelloThere banan = new HelloThere();
    System.out.println(banan.hello(name));


  }

  // Solution for the second task.
  /**
 * Seconds method for getting the user input.
 */
  public void seconds() {
    Scanner scanner = new Scanner(System.in);
    System.out.print("Enter hours, minutes and seconds: ");
    String[] inputValues = input.nextLine().split(" ");
    // Source: https://sentry.io/answers/how-do-i-convert-a-string-to-an-int-in-java/#:~:text=The%20two%20easiest%20ways%20to,()%20or%20Integer.valueOf()%20.
    // Convert strings to integers.
    int h = Integer.parseInt(inputValues[0]);
    int m = Integer.parseInt(inputValues[1]);
    int s = Integer.parseInt(inputValues[2]);

    Time time = new Time();
    int totalSeconds = time.toSeconds(h, m, s);
    System.out.println("In only seconds that is: " +  totalSeconds);
    
    // Close scanner
    scanner.close();
  }

  

  /**
 * Simulates being in a band by creating and printing details of an album.
 */
  public void imInaBand() {
    Album album = new Album("Wish you were here", 1975, "Pink Floyd");

    System.out.println(album.getName() + " was released in " + album.getYear() + " by " + album.getArtist());
  }

  
  
  /**
   * Solution for the fourth task.
   */
  public void bestAlbumsEver() {
    AlbumGenerator  albumGenerator = new AlbumGenerator();

    // Call the generateAlbums method to retrieve the arrays of the albums
    Album[] albums = albumGenerator.generateAlbums();

    // Print out the albums using for loop
    // Source: https://adevait.com/java/java-for-loops
    for (Album album : albums) {
      System.out.println(album.getName() + " was released in " + album.getYear() + " by " + album.getArtist());
    }


  }

  /**
   * Solution for the fifth task.
   */
  public void workingWithArrays() {
    int[] array = {5, 2, 6, 4, 1, 3, 7, 9, 8};
    // Create an instance of the class arry
    ArrayAlgorithms arrayAlgorithms = new ArrayAlgorithms();

    // Calculate the avrg of the array and print it out
    double arrayAverage =  arrayAlgorithms.average(array);
    System.out.println("Avrg: " +  arrayAverage);

    int arrayMaxValue = arrayAlgorithms.maxValue(array);
    System.out.println("Largest value is: " +  arrayMaxValue);

    int arrayMininIndex = arrayAlgorithms.minIndex(array);
    System.out.println("Index of smallest int is at: " +  arrayMininIndex);


    int[] shuffledArray = arrayAlgorithms.shuffle(array);
    System.out.println("Shuffled array: ");
    
    // Iterate through each element of the shuffled array and print the current element
    for (int i = 0; i < shuffledArray.length; i++) {
      System.out.print(shuffledArray[i]);

      // If it's not the last element, print a comma and space
      if (i != shuffledArray.length - 1) {
        System.out.print(", ");

      }
    }

  }

  /**
   * Starting point of the first assignment.
   *
   * @param args is not used.
   */
  public static void main(String[] args) {
    

    // we create a scanner object to work with
    // it is advised to create one and only one scanner for a specific stream in the whole 
    // application scanners should be closed when you are done and this also closes 
    // the underlying stream
    Scanner consoleInput = new Scanner(System.in, "UTF-8");

    App app = new App(consoleInput);

    // Task 1
    // app.helloThere();

    // Task 2
    // app.seconds();

    // Task 3
    //  app.imInaBand();

    // Task 4 
    app.bestAlbumsEver();

    // Task 5
    // app.workingWithArrays();


    // If you are going for the higher grades you can uncomment the following lines
    // and implement the methods in the GradeC class.
    // GradeC gradeC = new GradeC();
    // gradeC.calculator(consoleInput);
    // gradeC.arrays2D();
    // gradeC.band();


    // now we are exiting the application so time to close the scanner.
    consoleInput.close();
  }
}
